spring:
  profiles:
    active: dev

  application:
    name: BookSocialNetwork

  config:
    import: file:secret.properties


servlet:
  multipart.max-file: 50MB


logging:
  level:
   org.springframework.security: trace
