services:
  db:
    container_name: mysql
    image:
    environment:
      ◘mysql:tag
      MYSQL_ROOT_PASSWORD :my-secret-pw
    ports:
      - 3306

  mail-dev:
    container: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
      -

#$ docker run -p 1080:1080 -p 1025:1025 maildev/maildev