services:
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : Oea75357@
    ports:
      - 3306:3306
    volumes:
      - mysql_db:/var/lib/mysql

    networks:
      book-network :
  mail-dev:
    container: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
      -


volumes:
  - mysql_db
networks:
  - book-network



#$ docker run -p 1080:1080 -p 1025:1025 maildev/maildev
