name: bsn_pipeline
on:
  push: 
    branches: main
    paths:
      - "docker-compose.yml"
      - "Dockerfile"
      - src/**
      - .github/workflows/pipeline.yml
   
jobs:
  compile:
    name: compile the project
    runs-on: ubuntu-slim
    steps:
      - name: checkout the code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth : 0
          
      - name: setup jdk
        uses: actions/setup-java@v5.2.0
        with:
         java-version: 21
         distribution: 'corretto'
         
      - name: compile the code
        run: ./mvnw clean compile
      
  build_jar:
    name: build the jar file
    runs-on: ubuntu-slim
    needs: [compile]
    steps:
      - name : extract the version
        run: ./mvnw clean package -DskipTests
    
  build_image:
    name: login and build the image docker
    runs-on: ubuntu-slim
    needs: [build_jar]
    steps:
      - name: extract the project version
        id: extract_docker
        run: |
         echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name : login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER.TOKEN}}

      - name : build image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platform: linux/amd64
          tag: ${{secrets.DOCKER_USERNAME}}/bsn:${{steps.extract.outputs.VERSION}} ,
               ${{secrets.DOCKER_USERNAME}}/bsn:latest


      
